version: "3.8"

services:
  frontend:
    image: store-frontend:1.0.0
    container_name: store-frontend
    build:
      context: ./front
      dockerfile: Dockerfile
    networks:
      - store-net
    ports:
      - 8081:8081
    env_file:
      - .env

  nginx-proxy:
    build:
      context: "./proxy"
      dockerfile: "Dockerfile"
    image: "store-nginx-proxy"
    volumes:
      - "./proxy:/proxy"
    ports:
      - "80:80"
    networks:
      - store-net
    depends_on:
      - frontend

networks:
  store-net:
    driver: bridge